wagtail/contrib/redirects/urls.py
from django.conf.urls import url

from wagtail.contrib.redirects import views

app_name = 'wagtailredirects'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^(\d+)/$', views.edit, name='edit'),
    url(r'^(\d+)/delete/$', views.delete, name='delete'),
]

wagtail/contrib/redirects/templates/wagtailredirects/add.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% trans "Add redirect" %}{% endblock %}
{% block content %}
    {% trans "Add redirect" as add_red_str %}
    {% include "wagtailadmin/shared/header.html" with title=add_red_str icon="redirect" %}

    {% if form.non_field_errors %}
        <div class="messages">
            <ul>
                {% for error in form.non_field_errors %}
                    <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <form action="{% url 'wagtailredirects:add' %}" method="POST" class="nice-padding" novalidate>
        {% csrf_token %}

        <ul class="fields">
            {% for field in form.visible_fields %}
                {% include "wagtailadmin/shared/field_as_li.html" %}
            {% endfor %}

            <li>
                <input type="submit" value="{% trans 'Save' %}" class="button" />
            </li>
        </ul>
    </form>

{% endblock %}

{% block extra_js %}
    {{ block.super }}
    {% include "wagtailadmin/pages/_editor_js.html" %}
    {{ form.media.js }}
{% endblock %}

{% block extra_css %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/confirm_delete.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with title=redirect.title %}Delete redirect {{ title }}{% endblocktrans %}{% endblock %}
{% block content %}
    {% trans "Delete" as delete_str %}
    {% include "wagtailadmin/shared/header.html" with title=delete_str subtitle=redirect.title icon="redirect" %}

    <div class="row row-flush nice-padding">
        <p>{% trans "Are you sure you want to delete this redirect?" %}</p>
        <form action="{% url 'wagtailredirects:delete' redirect.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="{% trans 'Yes, delete' %}" class="button serious" />
        </form>
    </div>

{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/edit.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% blocktrans with title=redirect.title %}Editing {{ title }}{% endblocktrans %}{% endblock %}
{% block content %}
    {% trans "Editing" as editing_str %}
    {% include "wagtailadmin/shared/header.html" with title=editing_str subtitle=redirect.title icon="redirect" %}

    {% if form.non_field_errors %}
        <div class="messages">
            <ul>
                {% for error in form.non_field_errors %}
                    <li class="error">{{ error }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <form action="{% url 'wagtailredirects:edit' redirect.id %}" method="POST" class="nice-padding" novalidate>
        {% csrf_token %}

        <ul class="fields">
            {% for field in form.visible_fields %}
                {% include "wagtailadmin/shared/field_as_li.html" %}
            {% endfor %}

            <li>
                <input type="submit" value="{% trans 'Save' %}" class="button" />
                {% if user_can_delete %}
                    <a href="{% url 'wagtailredirects:delete' redirect.id %}" class="button button-secondary no">{% trans "Delete redirect" %}</a>
                {% endif %}
            </li>
        </ul>
    </form>

{% endblock %}

{% block extra_js %}
    {{ block.super }}
    {% include "wagtailadmin/pages/_editor_js.html" %}
    {{ form.media.js }}
{% endblock %}

{% block extra_css %}
    {{ block.super }}
    {{ form.media.css }}
{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/index.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% trans "Redirects" %}{% endblock %}

{% block extra_js %}
    {{ block.super }}
    <script>
        window.headerSearch = {
            url: "{% url 'wagtailredirects:index' %}",
            termInput: "#id_q",
            targetOutput: "#redirects-results"
        }
    </script>
{% endblock %}

{% block content %}
    {% trans "Redirects" as redirects_str %}
    {% trans "Add redirect" as add_str %}
    {% if user_can_add %}
        {% include "wagtailadmin/shared/header.html" with title=redirects_str icon="redirect" add_link="wagtailredirects:add" add_text=add_str search_url="wagtailredirects:index" %}
    {% else %}
        {% include "wagtailadmin/shared/header.html" with title=redirects_str icon="redirect" search_url="wagtailredirects:index" %}
    {% endif %}

    <div class="nice-padding">
        <div id="redirects-results" class="redirects">
            {% include "wagtailredirects/results.html" %}
        </div>
    </div>
    
{% endblock %}

wagtail/contrib/redirects/templates/wagtailredirects/list.html
{% load i18n %}
<table class="listing">
    <col width="35%"/>
    <col width="30%"/>
    <col width="25%"/>
    <col />
    <thead>
        <tr>
            <th class="title">
                {% if not is_searching %}
                    <a href="{% url 'wagtailredirects:index' %}{% if not ordering == "old_path" %}?ordering=old_path{% endif %}" class="icon icon-arrow-down-after {% if ordering == "old_path" %}teal{% endif %}">
                        {% trans "From" %}
                    </a>
                {% else %}
                    {% trans "From" %}
                {% endif %}
            </th>
            <th>{% trans "Site" %}</th>
            <th>{% trans "To" %}</th>
            <th class="type">{% trans "Type" %}</th>
        </tr>
    </thead>
    <tbody>
        {% for redirect in redirects %}
            <tr>
                <td class="title">
                    <h2><a href="{% url 'wagtailredirects:edit' redirect.id %}" title="{% trans 'Edit this redirect' %}">{{ redirect.title }}</a></h2>
                </td>
                <td>
                    {% if redirect.site %}{{ redirect.site }}{% endif %}
                </td>
                <td>
                    {% if redirect.redirect_page %}
                        <a href="{% url 'wagtailadmin_pages:edit' redirect.redirect_page.id %}" class="nolink">{{ redirect.redirect_page.title }}</a>
                    {% else %}
                        {{ redirect.link }}
                    {% endif %}
                </td>
                <td class="type"><div class="status-tag {% if redirect.is_permanent %}primary{% endif %}">{{ redirect.get_is_permanent_display }}</div></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

wagtail/contrib/redirects/templates/wagtailredirects/results.html
{% load i18n %}
{% if redirects %}
    {% if query_string %}
        <h2>
        {% blocktrans count counter=redirects.paginator.count %}
            There is one match
        {% plural %}
            There are {{ counter }} matches
        {% endblocktrans %}
        </h2>
    {% endif %}

    {% include "wagtailredirects/list.html" %}

    {% include "wagtailadmin/shared/pagination_nav.html" with items=redirects is_searching=query_string linkurl="wagtailredirects:index" %}
{% else %}
     {% if query_string %}
         <p>{% blocktrans %}Sorry, no redirects match "<em>{{ query_string }}</em>"{% endblocktrans %}
     {% else %}
        {% url 'wagtailredirects:add' as wagtailredirects_add_redirect_url %}
        <p>{% blocktrans %}No redirects have been created. Why not <a href="{{ wagtailredirects_add_redirect_url }}">add one</a>?{% endblocktrans %}</p>
    {% endif %}
{% endif %}